@extends('admin.layouts.app')
@section('title', ($item->exists ? 'Edit ' : 'Tambah ').$title)
@section('content')
<form method="POST" enctype="multipart/form-data" action="{{ $item->exists ? route('admin.'.$route.'.update',$item) : route('admin.'.$route.'.store') }}" class="max-w-3xl space-y-5 rounded-xl border border-slate-200 bg-white p-6">@csrf @if($item->exists) @method('PUT') @endif
<div><label class="text-sm font-medium">Judul</label><input name="title" value="{{ old('title',$item->title) }}" class="mt-1 w-full rounded-md border-slate-300" required></div>
@if($slug)<div><label class="text-sm font-medium">Slug <span class="text-slate-400">(otomatis bila kosong)</span></label><input name="slug" value="{{ old('slug',$item->slug) }}" class="mt-1 w-full rounded-md border-slate-300"></div>@endif
@if($route === 'articles')<div><label class="text-sm font-medium">Ringkasan</label><textarea name="excerpt" class="mt-1 w-full rounded-md border-slate-300">{{ old('excerpt',$item->excerpt) }}</textarea></div><div><label class="text-sm font-medium">Isi artikel</label><textarea name="content" rows="10" class="mt-1 w-full rounded-md border-slate-300" required>{{ old('content',$item->content) }}</textarea></div>@endif
@if($route === 'videos')<div><label class="text-sm font-medium">URL video</label><input type="url" name="video_url" value="{{ old('video_url',$item->video_url) }}" class="mt-1 w-full rounded-md border-slate-300" required></div><div><label class="text-sm font-medium">Deskripsi</label><textarea name="description" class="mt-1 w-full rounded-md border-slate-300">{{ old('description',$item->description) }}</textarea></div>@endif
@if($route === 'flyers')<div><label class="text-sm font-medium">Deskripsi</label><textarea name="description" class="mt-1 w-full rounded-md border-slate-300">{{ old('description',$item->description) }}</textarea></div>@endif
@if($route === 'webinars')<div class="grid gap-4 sm:grid-cols-2"><div><label class="text-sm font-medium">Narasumber</label><input name="speaker" value="{{ old('speaker',$item->speaker) }}" class="mt-1 w-full rounded-md border-slate-300"></div><div><label class="text-sm font-medium">Tanggal & waktu</label><input type="datetime-local" name="webinar_date" value="{{ old('webinar_date', optional($item->webinar_date)->format('Y-m-d\\TH:i')) }}" class="mt-1 w-full rounded-md border-slate-300" required></div><div><label class="text-sm font-medium">Platform</label><input name="platform" value="{{ old('platform',$item->platform) }}" class="mt-1 w-full rounded-md border-slate-300"></div><div><label class="text-sm font-medium">Link pendaftaran</label><input type="url" name="registration_url" value="{{ old('registration_url',$item->registration_url) }}" class="mt-1 w-full rounded-md border-slate-300" required></div></div><div><label class="text-sm font-medium">Deskripsi</label><textarea name="description" class="mt-1 w-full rounded-md border-slate-300">{{ old('description',$item->description) }}</textarea></div>@endif
@if($upload)<div><label class="text-sm font-medium">{{ $uploadLabel }}</label><input type="file" accept="image/*" name="{{ $upload }}" class="mt-1 block w-full text-sm">@if($item->{$upload})<p class="mt-1 text-xs text-slate-400">File saat ini tersimpan.</p>@endif</div>@endif
@if($publishedAt)<div><label class="text-sm font-medium">Tanggal publikasi</label><input type="datetime-local" name="published_at" value="{{ old('published_at', optional($item->published_at)->format('Y-m-d\\TH:i')) }}" class="mt-1 w-full rounded-md border-slate-300"></div>@endif
<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_published" value="1" @checked(old('is_published',$item->exists ? $item->is_published : true))> Publikasikan</label><div class="flex gap-3"><button class="rounded-md bg-teal-500 px-4 py-2 text-sm font-semibold text-navy-950">Simpan</button><a href="{{ route('admin.'.$route.'.index') }}" class="px-4 py-2 text-sm text-slate-600">Batal</a></div></form>
@endsection
